version: 2.1
orbs:
  # orbs contain basic recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
  # different jobs are calles later in the workflows sections
workflows:
  main:
    jobs:
      - build:
          filters:
              branches:
                only:
                  - master
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.15"
    executor: node/default
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      # Use root level package.json to install dependencies in the frontend app
      - restore_cache:
          key: v1-deps-{{ checksum "udagram/udagram-frontend/package-lock.json" }}
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - save_cache:
          key: v1-deps-{{ checksum "udagram/udagram-frontend/package-lock.json" }}
          paths: 
            - node_modules
      # Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
      # Build the frontend app
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # deploy the frontend app      
      - run:
          name: API deploy
          command: |
            npm run frontend:deploy      
      # Install dependencies in the the backend API
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      # Build the backend API      
      - run:
          name: API Build
          command: |
            npm run api:build
      # deploy the backend API      
      - run:
          name: API deploy
          command: |
            npm run api:deploy
